site_name: TI Portfolio Project Game-controller
site_description: HBO-ICT Technische Informatica Portfolio
site_author: HBO-ICT
copyright: Copyright 2023 Hogeschool van Amsterdam

theme:
    name: material
    custom_dir: mdocotion/
    logo: assets/controller-icon.svg
    favicon: assets/controller-icon.svg
    features:
        - navigation.sections
        - content.tabs.link
    icon:
        admonition:
            note: octicons/tag-16
            abstract: octicons/checklist-16
            info: octicons/info-16
            tip: octicons/squirrel-16
            success: octicons/check-16
            question: octicons/question-16
            warning: octicons/alert-16
            failure: octicons/x-circle-16
            danger: octicons/zap-16
            bug: octicons/bug-16
            example: octicons/beaker-16
            quote: octicons/quote-16

plugins:
    - search
    - mermaid2
    - awesome-pages
    - mkdocs-video
    - section-index
    - autolinks
    - material-extensions
    - macros:
          modules: [mkdocs_macros_mdocotion]

markdown_extensions:
    - attr_list
    - admonition
    - pymdownx.details
    - md_in_html
    - fenced_code
    - tables
    - pymdownx.highlight:
          linenums: true
          use_pygments: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.tasklist:
          custom_checkbox: true
          clickable_checkbox: true
    - pymdownx.superfences:
          custom_fences:
                - name: mermaid
                  class: mermaid
                  format: !!python/name:pymdownx.superfences.fence_code_format