site_name: TI Portfolio Project Game-controller
site_description: HBO-ICT Technische Informatica Portfolio
site_author: HBO-ICT
copyright: Copyright 2023 Hogeschool van Amsterdam

theme:
    name: material
    custom_dir: mdocotion/
    logo: assets/controller-icon.svg
    favicon: assets/controller-icon.svg
    features:
        - navigation.sections
        - content.tabs.link

plugins:
    - search
    - mermaid2
    - awesome-pages
    - mkdocs-video
    - section-index
    - autolinks
    - macros:
          modules: [mkdocs_macros_mdocotion]

markdown_extensions:
    - attr_list
    - admonition
    - pymdownx.details
    - md_in_html
    - fenced_code
    - pymdownx.highlight:
          linenums: true
          use_pygments: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.tasklist:
          custom_checkbox: true
          clickable_checkbox: true
    - pymdownx.superfences:
          custom_fences:
                - name: mermaid
                  class: mermaid
                  format: !!python/name:pymdownx.superfences.fence_code_format
